### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by CFlanc** [kaustubh03/amelia_2.0#1]
Unable to install all dependencies since there is no requirements.txt included

**Comment by kaustubh03** [comment]
you can refer to all the imports in the starting of the script. If it still doesn't work lemme know I'll include the requirements.txt soon.

**Comment by CFlanc** [comment]
I have already tried that '
hope to see the requirements.txt soon.

**Comment by kaustubh03** [comment]
i will asap. Note- This will work only on windows due to AVBIN dependency.

**Comment by pvskand** [comment]
Could you please add the instructions to run the code.
